# TCL File Generated by Component Editor 13.1
# Sun Apr 27 12:33:33 PDT 2014
# DO NOT MODIFY


# 
# i2c_master "i2c_master" v1.0
#  2014.04.27.12:33:33
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module i2c_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME i2c_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME i2c_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2c_master_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file i2c_master_bit_ctrl.v VERILOG PATH i2c/trunk/rtl/verilog/i2c_master_bit_ctrl.v
add_fileset_file i2c_master_byte_ctrl.v VERILOG PATH i2c/trunk/rtl/verilog/i2c_master_byte_ctrl.v
add_fileset_file i2c_master_defines.v VERILOG PATH i2c/trunk/rtl/verilog/i2c_master_defines.v
add_fileset_file i2c_master_top.v VERILOG PATH i2c/trunk/rtl/verilog/i2c_master_top.v TOP_LEVEL_FILE
add_fileset_file timescale.v VERILOG PATH i2c/trunk/rtl/verilog/timescale.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL i2c_master_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file i2c_master_bit_ctrl.v VERILOG PATH i2c/trunk/rtl/verilog/i2c_master_bit_ctrl.v
add_fileset_file i2c_master_byte_ctrl.v VERILOG PATH i2c/trunk/rtl/verilog/i2c_master_byte_ctrl.v
add_fileset_file i2c_master_defines.v VERILOG PATH i2c/trunk/rtl/verilog/i2c_master_defines.v
add_fileset_file i2c_master_top.v VERILOG PATH i2c/trunk/rtl/verilog/i2c_master_top.v
add_fileset_file timescale.v VERILOG PATH i2c/trunk/rtl/verilog/timescale.v


# 
# parameters
# 
add_parameter ARST_LVL STD_LOGIC_VECTOR 0
set_parameter_property ARST_LVL DEFAULT_VALUE 0
set_parameter_property ARST_LVL DISPLAY_NAME ARST_LVL
set_parameter_property ARST_LVL WIDTH 2
set_parameter_property ARST_LVL TYPE STD_LOGIC_VECTOR
set_parameter_property ARST_LVL UNITS None
set_parameter_property ARST_LVL ALLOWED_RANGES 0:3
set_parameter_property ARST_LVL HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink_1
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 wb_dat_i writedata Input 8
add_interface_port avalon_slave_0 wb_dat_o readdata Output 8
add_interface_port avalon_slave_0 wb_we_i write Input 1
add_interface_port avalon_slave_0 wb_stb_i chipselect Input 1
add_interface_port avalon_slave_0 wb_cyc_i chipselect Input 1
add_interface_port avalon_slave_0 wb_ack_o waitrequest_n Output 1
add_interface_port avalon_slave_0 wb_adr_i address Input 3
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink wb_clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink arst_i reset_n Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender wb_inta_o irq Output 1


# 
# connection point reset_sink_1
# 
add_interface reset_sink_1 reset end
set_interface_property reset_sink_1 associatedClock ""
set_interface_property reset_sink_1 synchronousEdges NONE
set_interface_property reset_sink_1 ENABLED true
set_interface_property reset_sink_1 EXPORT_OF ""
set_interface_property reset_sink_1 PORT_NAME_MAP ""
set_interface_property reset_sink_1 CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port reset_sink_1 wb_rst_i reset Input 1


# 
# connection point scl_pad_i
# 
add_interface scl_pad_i conduit end
set_interface_property scl_pad_i associatedClock ""
set_interface_property scl_pad_i associatedReset ""
set_interface_property scl_pad_i ENABLED true
set_interface_property scl_pad_i EXPORT_OF ""
set_interface_property scl_pad_i PORT_NAME_MAP ""
set_interface_property scl_pad_i CMSIS_SVD_VARIABLES ""
set_interface_property scl_pad_i SVD_ADDRESS_GROUP ""

add_interface_port scl_pad_i scl_pad_i writeresponserequest_n Input 1


# 
# connection point scl_pad_o
# 
add_interface scl_pad_o conduit end
set_interface_property scl_pad_o associatedClock ""
set_interface_property scl_pad_o associatedReset ""
set_interface_property scl_pad_o ENABLED true
set_interface_property scl_pad_o EXPORT_OF ""
set_interface_property scl_pad_o PORT_NAME_MAP ""
set_interface_property scl_pad_o CMSIS_SVD_VARIABLES ""
set_interface_property scl_pad_o SVD_ADDRESS_GROUP ""

add_interface_port scl_pad_o scl_pad_o writeresponsevalid_n Output 1


# 
# connection point scl_padoen_oe
# 
add_interface scl_padoen_oe conduit end
set_interface_property scl_padoen_oe associatedClock ""
set_interface_property scl_padoen_oe associatedReset ""
set_interface_property scl_padoen_oe ENABLED true
set_interface_property scl_padoen_oe EXPORT_OF ""
set_interface_property scl_padoen_oe PORT_NAME_MAP ""
set_interface_property scl_padoen_oe CMSIS_SVD_VARIABLES ""
set_interface_property scl_padoen_oe SVD_ADDRESS_GROUP ""

add_interface_port scl_padoen_oe scl_padoen_o writeresponsevalid_n Output 1


# 
# connection point sda_pad_i
# 
add_interface sda_pad_i conduit end
set_interface_property sda_pad_i associatedClock ""
set_interface_property sda_pad_i associatedReset ""
set_interface_property sda_pad_i ENABLED true
set_interface_property sda_pad_i EXPORT_OF ""
set_interface_property sda_pad_i PORT_NAME_MAP ""
set_interface_property sda_pad_i CMSIS_SVD_VARIABLES ""
set_interface_property sda_pad_i SVD_ADDRESS_GROUP ""

add_interface_port sda_pad_i sda_pad_i writeresponserequest_n Input 1


# 
# connection point sda_pad_o
# 
add_interface sda_pad_o conduit end
set_interface_property sda_pad_o associatedClock ""
set_interface_property sda_pad_o associatedReset ""
set_interface_property sda_pad_o ENABLED true
set_interface_property sda_pad_o EXPORT_OF ""
set_interface_property sda_pad_o PORT_NAME_MAP ""
set_interface_property sda_pad_o CMSIS_SVD_VARIABLES ""
set_interface_property sda_pad_o SVD_ADDRESS_GROUP ""

add_interface_port sda_pad_o sda_pad_o writeresponsevalid_n Output 1


# 
# connection point sda_padoen_oe
# 
add_interface sda_padoen_oe conduit end
set_interface_property sda_padoen_oe associatedClock ""
set_interface_property sda_padoen_oe associatedReset ""
set_interface_property sda_padoen_oe ENABLED true
set_interface_property sda_padoen_oe EXPORT_OF ""
set_interface_property sda_padoen_oe PORT_NAME_MAP ""
set_interface_property sda_padoen_oe CMSIS_SVD_VARIABLES ""
set_interface_property sda_padoen_oe SVD_ADDRESS_GROUP ""

add_interface_port sda_padoen_oe sda_padoen_o writeresponsevalid_n Output 1

